
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        codefield.setVisible(false);
    }
    private Connection getConnection() {
        ConfigDb db = new ConfigDb();
        return db.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roles = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        coach = new javax.swing.JRadioButton();
        phoneInf = new javax.swing.JTextField();
        admoun = new javax.swing.JRadioButton();
        emailInf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageAvatar1 = new com.raven.avatar.ImageAvatar();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fullname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        passInf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        adh = new javax.swing.JRadioButton();
        code = new javax.swing.JLabel();
        codefield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Email :");

        roles.add(coach);
        coach.setText("Coach");
        coach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachActionPerformed(evt);
            }
        });

        phoneInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneInfActionPerformed(evt);
            }
        });

        roles.add(admoun);
        admoun.setText("Admin");
        admoun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admounActionPerformed(evt);
            }
        });

        emailInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailInfActionPerformed(evt);
            }
        });

        jLabel8.setText("Pasword :");

        jLabel9.setText("I've an account");

        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Log in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("SignUp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 700));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("flifel gym");

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymIcon.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setBackground(new java.awt.Color(0, 102, 102));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("SignUp");

        jLabel4.setText("Phone Number");

        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });

        jLabel5.setText("Full Name");

        passInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passInfActionPerformed(evt);
            }
        });

        roles.add(adh);
        adh.setText("Member");
        adh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adhActionPerformed(evt);
            }
        });

        codefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codefieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(coach)
                        .addGap(18, 18, 18)
                        .addComponent(admoun)
                        .addGap(18, 18, 18)
                        .addComponent(adh, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailInf, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(phoneInf)
                            .addComponent(fullname)
                            .addComponent(passInf))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(codefield, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneInf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailInf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passInf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coach)
                    .addComponent(admoun)
                    .addComponent(adh))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codefield, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton1))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachActionPerformed
        codefield.setVisible(true);
        code.setText("Coach Code : ");
    }//GEN-LAST:event_coachActionPerformed

    private void phoneInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneInfActionPerformed

    private void emailInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailInfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LogIn f1 ;
        f1 = new LogIn();

        f1.pack();
        f1.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    private boolean isNumeric(String ch){
        if (ch.isEmpty()) {
            return false;
        }
        else{
            for (int i = 0; i < ch.length(); i++) {
                if (ch.charAt(i)>= '0' && ch.charAt(i)<='9') {    
                }
                else{
                    return false;
                }
                
            }
        }
        return true;
    }
    private boolean VefPhone(String ch){
        return ch.length()==8 && isNumeric(ch);

    }
    
    private boolean VefEmail(String ch) {
        if (ch == null) return false;

        String emailRegex = "^[\\w.-]+@[\\w.-]+\\.[A-Za-z]{2,}$";
        return ch.matches(emailRegex);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int personId= -1;
        
        if (!VefEmail(emailInf.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid Email", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!VefPhone(phoneInf.getText())) {
            JOptionPane.showMessageDialog(null, "Invalid Phone", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Connection con = getConnection();
        if (con != null) {
            System.out.println("Connection success");
            
            String fulname = fullname.getText();
            String ph = phoneInf.getText();
            String email = emailInf.getText();
            String pass = passInf.getText();

            String selectedRole = "";
            if (coach.isSelected()) {
                selectedRole = "coach";
            } else if (admoun.isSelected()) {
                selectedRole = "admin";
                
            } else if (adh.isSelected()) {
                selectedRole = "adherent";
            } else {
                JOptionPane.showMessageDialog(null, "Please select a role", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            String query = "INSERT INTO person(name, email, password, role,phone_number) VALUES (?, ?, ?, ?, ?)";

            try (PreparedStatement pst = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {
                pst.setString(1, fulname);
                pst.setString(2, email);
                pst.setString(3, pass);
                pst.setString(4, selectedRole);
                pst.setString(5, ph);
                
                int affectedRows = pst.executeUpdate();
                if (affectedRows == 0) {
                    throw new SQLException("Creating person failed, no rows affected.");
                }

                try (ResultSet generatedKeys = pst.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        personId = generatedKeys.getInt(1);

                        if (selectedRole.equalsIgnoreCase("admin")) {
                            String adminQuery = "INSERT INTO admin(id_admin) VALUES (?)";
                            try (PreparedStatement adminPst = con.prepareStatement(adminQuery)) {
                                adminPst.setInt(1, personId);
                                adminPst.executeUpdate();
                            }
                        } else if (selectedRole.equalsIgnoreCase("coach")) {
                            String coachQuery = "INSERT INTO coach(id_coach, speciality) VALUES (?, ?)";
                            try (PreparedStatement coachPst = con.prepareStatement(coachQuery)) {
                                coachPst.setInt(1, personId);
                                coachPst.setString(2, "misculation");
                                coachPst.executeUpdate();
                            }
                        }
                        else if (selectedRole.equalsIgnoreCase("adherent")) {
                        String adhQuery = "INSERT INTO adherent(id_adherent,current_subscription_end) VALUES (?, ?)";
                        String payQuery = "INSERT INTO payment(id_adherent,amount,payment_date,subscription_end) VALUES (?, ?,?,?)";
                        String mo=codefield.getText();
                        int amount=0;

                        if(Integer.parseInt(mo)==1){amount=100;}
                        else if (Integer.parseInt(mo)==3){amount=270;}
                        else if ((Integer.parseInt(mo)==6)){amount=520;}
                        else if ((Integer.parseInt(mo)==12)){amount=1100;}
                        
                        LocalDate today = LocalDate.now();
                        LocalDate futureDate = today.plusMonths(Integer.parseInt(mo));
                        java.sql.Date sqlDate = java.sql.Date.valueOf(futureDate);
                        java.sql.Date sqlTodayDate = java.sql.Date.valueOf(today);
                            try (PreparedStatement adhPst = con.prepareStatement(adhQuery)) {
                                adhPst.setInt(1, personId);
                                adhPst.setDate(2, sqlDate);
                                adhPst.executeUpdate();
                            }
                            try (PreparedStatement payPst = con.prepareStatement(payQuery)) {
                                payPst.setInt(1, personId);
                                payPst.setInt(2, amount);
                                payPst.setDate(3, sqlTodayDate);
                                payPst.setDate(4, sqlDate);
                                payPst.executeUpdate();
                            }
                        
                        
                        }
                    }

                }

                if(personId!= -1){
                    System.out.println("Insertion avec succès");
                    if(selectedRole.equalsIgnoreCase("admin")) {
                        AdminInf ad = new AdminInf();
                        ad.pack();
                        ad.setVisible(true);

                        this.dispose();
                    } 
                    else if (selectedRole.equalsIgnoreCase("coach")) {
                        CoachInf c1 = new CoachInf(personId);
                        c1.pack();
                        c1.setVisible(true);
                        this.dispose();
                    }
                    else if (selectedRole.equalsIgnoreCase("adherent")) {
                        AdherantInf a1 = new AdherantInf(personId);
                        a1.pack();
                        a1.setVisible(true);
                        
                        this.dispose();
                    }
                }else {
                    System.out.println("Insertion échouée personId = -1");
                }

            } catch (SQLException e) {
                e.printStackTrace();
                System.out.println("Error");
            }
        } else {
            System.out.println("Connection failed");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void adhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adhActionPerformed
        codefield.setVisible(true);
        code.setText("Nombre de mois : ");
    }//GEN-LAST:event_adhActionPerformed

    private void codefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codefieldActionPerformed
                // TODO add your handling code here:
    }//GEN-LAST:event_codefieldActionPerformed

    private void admounActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admounActionPerformed
        codefield.setVisible(true);
        code.setText("Admin Code : ");
    }//GEN-LAST:event_admounActionPerformed

    private void passInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passInfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passInfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adh;
    private javax.swing.JRadioButton admoun;
    private javax.swing.JRadioButton coach;
    private javax.swing.JLabel code;
    private javax.swing.JTextField codefield;
    private javax.swing.JTextField emailInf;
    private javax.swing.JTextField fullname;
    private com.raven.avatar.ImageAvatar imageAvatar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField passInf;
    private javax.swing.JTextField phoneInf;
    private javax.swing.ButtonGroup roles;
    // End of variables declaration//GEN-END:variables
}
